# Generated by Django 4.2.5 on 2023-09-24 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='department name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department')),
            ],
            options={
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='middle name')),
                ('position', models.CharField(max_length=255, verbose_name='position')),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary in rubles')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='staff.department')),
            ],
            options={
                'verbose_name_plural': 'employees',
                'ordering': ['-hire_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_combination_of_name_and_parent'),
        ),
    ]
